''' <summary>One row of the notifications table (generated by AlertService).</summary>
Public Class Notification
    Public Property NotificationId As Integer
    Public Property BusinessId As Integer
    Public Property ModuleName As String = ""       ' column "module" - see ModuleNames constants
    Public Property RelatedId As Integer            ' id of the record the alert is about
    Public Property Priority As String = "Warning"  ' Info / Warning / Urgent
    Public Property Message As String = ""
    Public Property DueDate As Date
    Public Property IsRead As Boolean
    Public Property CreatedAt As Date

    ' Display only (filled from a JOIN, not saved)
    Public Property BusinessName As String = ""
End Class
